Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,38 +22,63 @@ jobs:
         cache: true
 
 
-    - name: Find Flutter Project
+    - name: Locate Flutter Project
+      shell: bash
       run: |
-        echo "Searching..."
-        PROJECT=$(find . -name pubspec.yaml -exec dirname {} \; | head -1)
-        echo "PROJECT=$PROJECT"
-        echo "PROJECT=$PROJECT" >> $GITHUB_ENV
+        echo "Searching Flutter project..."
+
+        PUBSPEC=$(find "$GITHUB_WORKSPACE" -name pubspec.yaml | head -n 1)
+
+        if [ -z "$PUBSPEC" ]; then
+          echo "ERROR: pubspec.yaml not found"
+          exit 1
+        fi
+
+        PROJECT_DIR=$(dirname "$PUBSPEC")
+
+        echo "Found:"
+        echo "$PROJECT_DIR"
+
+        echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
 
 
     - name: Flutter Doctor
-      run: flutter doctor -v
+      run: |
+        flutter doctor -v
 
 
     - name: Flutter Pub Get
+      shell: bash
       run: |
-        cd "$PROJECT"
+        cd "$PROJECT_DIR"
+        echo "Current:"
+        pwd
         flutter pub get
 
 
     - name: Flutter Clean
+      shell: bash
       run: |
-        cd "$PROJECT"
+        cd "$PROJECT_DIR"
         flutter clean
 
 
     - name: Build APK
+      shell: bash
       run: |
-        cd "$PROJECT"
+        cd "$PROJECT_DIR"
         flutter build apk --release
+
+
+    - name: Find APK
+      shell: bash
+      run: |
+        find "$PROJECT_DIR" -name "*.apk"
 
 
     - name: Upload APK
       uses: actions/upload-artifact@v4
       with:
         name: OKN_DSP_BP1048P4_APK
-        path: ${{ env.PROJECT }}/build/app/outputs/flutter-apk/app-release.apk
+        path: |
+          **/app-release.apk
